name: bip32_mnemonic
description: An implementation of the BIP32 spec for deriving private keys from mnemonic phrases
version: 1.0.0
homepage: https://github.com/variadiclabs/bip32-mnemonic

environment:
  sdk: '>=2.14.4 <3.0.0'

dev_dependencies:
  bip39: ^1.0.6
  convert: ^3.0.2
  cryptography: ^2.0.5
  dartdoc: ^5.1.2
  lints: ^1.0.1
  pointycastle: ^3.6.2
  secp256k1: ^0.3.0
  test: ^1.21.4
  web3dart: ^2.4.1
